audit_header: false
title: Santa Clara Real Estate Video Blog with Brandon Montemayor
description: >-
  Our mission at Montemayor & Associates is to be your best resource for Santa
  Clara real estate advice. Whether you are a buyer, seller, or investor, our
  team of professionals can answer any questions you might have about real
  estate. If you are looking to buy or sell a home, you can get all the
  information and the latest updates, tips, and tricks from The Montemayor &
  Associates, your professional Santa Clara Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:
client:
  name: Brandon Montemayor
  title:
  license_number:
  about_markdown: >-
    Brandon Montemayor is the CEO and Founder of Montemayor & Associates, Inc.
    As Real Estate Professionals, Brandon’s team has remained in the top tier of
    producing real estate agents nationwide, earning the majority of their
    business from the referrals of current and past clients. Brandon and his
    team specialize in all aspects of residential real estate, investment sales,
    multi-unit, and relocations. Montemayor & Associates remains on the cutting
    edge of real estate technology, market information, and industry changes so
    that their client’s receive every advantage possible when buying or selling
    a home. Their “Client-First” philosophy ensures that every piece of advice
    passed along to their clients will best benefit their specific and unique
    situation.
  brand: Montemayor & Associates
  brokerage:
  market: Santa Clara
  address: '25101 The Old Road<br>Stevenson Ranch, CA 91381'
  phone: (661) 510-2789
  phone_type:
  phone2:
  phone2_type:
  email: Brandon@bringingyouhomescv.com
  url: 'http://bringingyouhomescv.com'
CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: 'http://myscvhomefinder.com/home_value'
  second_CTA_text: Home Search
  second_CTA_URL: >-
    http://myscvhomefinder.com/search#?q_limit=36&q_prioritize=agents.0.id=F207098400%7Coffice.id=FF7000252&mlsId=347&status=1%7C3&q_sort=createdAt-&q_offset=0
sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: What’s Your Santa Clara Home Worth?
    CTA_text: >-
      Are you thinking of selling your home or interested in learning about home
      prices in your neighborhood? We can help you.
    CTA_link_text: Free Home Value Report
    CTA_url: 'http://myscvhomefinder.com/home_value'
second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: Looking for a Santa Clara Home?
    CTA_text2: Search the entire MLS for your Santa Clara home.
    CTA_link_text2: Search the MLS
    CTA_url2: >-
      http://myscvhomefinder.com/search#?q_limit=36&q_prioritize=agents.0.id=F207098400%7Coffice.id=FF7000252&mlsId=347&status=1%7C3&q_sort=createdAt-&q_offset=0
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:
socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/bringingyouhomescv/?fref=ts'
  linkedin_url: 'https://www.linkedin.com/in/brandon-montemayor-58094635'
  youtube_url: 'https://www.youtube.com/channel/UCT7WdH4Tl9Ejd3yF3MgSRHg'
  twitter_url: 'https://twitter.com/BrandonRE_Pro'
  instagram_url:
  pinterest_url:
  zillow_url: 'http://www.zillow.com/profile/bmontemayor/'
  trulia_url: >-
    http://www.trulia.com/profile/brandon-montemayor-agent-santa-clarita-ca-zg2yw947/overview
  yelp_url: >-
    https://www.yelp.com/biz/brandon-montemayor-re-max-of-santa-clarita-santa-clarita
  podcast_url: >-
    https://itunes.apple.com/us/podcast/santa-clarita-valley-real/id1178772996?mt=2
podcast:
  title: Santa Clara Real Estate Podcast with Brandon Montemayor
  categories:
    - Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the Santa
    Clara Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from Montemayor & Associates - your
    professional Santa Clara Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in Santa Clara,
    home selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: Brandon Montemayor
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Santa Clara Real Estate Video Blog
  hero_background_hex: '#999999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg
site_colors:
  brand_color: '#a72429'
  theme_color: '#818286'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#000000'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: 'rgba(0, 0, 0, 0)'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'